import { Drug } from "../DrugCard";
const DrugInventoryList: Drug[] = [
  {
    brand: "Alysena",
    name: "28",
    dosage: [
      [100, "mcg"],
      [20, "mcg"],
    ],
    divider: "/",
    din: "02387883",
    quantity: [10, "TAB"],
  },
  {
    brand: "Sandoz",
    name: "Amlodipine",
    dosage: [[10, "mg"]],
    divider: "/",
    din: "​02284391​",
    quantity: [75, "TAB"],
  },
  {
    brand: "Apo",
    name: "Atorvastatin",
    dosage: [[40, "mg"]],
    divider: "/",
    din: "02295296",
    quantity: [36, "TAB"],
  },
  {
    brand: "Sandoz",
    name: "Candesartan",
    dosage: [[32, "mg"]],
    divider: "/",
    din: "02417340",
    quantity: [48, "TAB"],
  },
  {
    brand: "Humira",
    name: "",
    dosage: [
      [40, "mg"],
      [0.8, "mL"],
    ],
    divider: "/",
    din: "02258595​",
    quantity: [120, "mg"],
  },
  {
    brand: "Sandoz",
    name: "Metformin",
    dosage: [[500, "mg"]],
    divider: "/",
    din: "02246820",
    quantity: [175, "TAB"],
  },
  {
    brand: "Apo",
    name: "Mometasone",
    dosage: [[50, "mcg"]],
    divider: "/",
    din: "02403587",
    quantity: [9, "PACK"],
  },
  {
    brand: "Jamp",
    name: "Pantoprazole",
    dosage: [[40, "mg"]],
    divider: "/",
    din: "02357054​",
    quantity: [90, "TAB"],
  },
  {
    brand: "Oxycontin",
    name: "",
    dosage: [[10, "mg"]],
    divider: "/",
    din: "02240131",
    quantity: [42, "TAB"],
  },
  {
    brand: "Sandoz",
    name: "Ramipril",
    dosage: [[2.5, "mg"]],
    divider: "/",
    din: "02355922​",
    quantity: [56, "TAB"],
  },
  {
    brand: "Crestor",
    name: "Rosuvastatin",
    dosage: [[5, "mg"]],
    divider: "/",
    din: "02355922",
    quantity: [38, "TAB"],
  },
  {
    brand: "Teva",
    name: "Salbutamol",
    dosage: [[100, "mcg"]],
    divider: "/",
    din: "02326450",
    quantity: [700, "mcg"],
  },
  {
    brand: "Shingrix",
    name: "",
    dosage: [
      [50, "mcg"],
      [0.5, "mL"],
    ],
    divider: "/",
    din: "02468425​",
    quantity: [4, "PACK"],
  },
  {
    brand: "Snythroid",
    name: "",
    dosage: [[175, "mcg"]],
    divider: "/",
    din: "02172135​",
    quantity: [114, "TAB"],
  },
  {
    brand: "Vyvanse",
    name: "",
    dosage: [[60, "mg"]],
    divider: "/",
    din: "02347172",
    quantity: [73, "CAP"],
  },
];

export default DrugInventoryList;
